[package]
name = "badgine"
version = "0.1.0"
edition = "2021"
authors = ["Minus Kelvin <mark.carlson@minuskelvin.net>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cozy-chess = "0.2.1"
nohash = "0.2.0"
rand = "0.8.4"
